<?php

namespace ACSEO\Bundle\PHPUnitShowcaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HumainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HumainRepository extends EntityRepository
{
}