<?php

namespace ACSEO\Bundle\CacheShowcaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PassengerLuggageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerLuggageRepository extends EntityRepository
{
}